---

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure Mariadb is installed on Debian.
  apt:
    name: "{{ mariadb_packages }}"
    state: present

- name: Ensure Mariadb has selected state and enabled on boot.
  service:
    name: "{{ mariadb_service }}"
    state: "{{ mariadb_state }}"
    enabled: "{{ mariadb_enabled }}"

#- name: Removes anonymous user account for localhost
#  mysql_user:
#    name: ''
#    host: localhost
#    state: absent

- name: Create a new database with name 'site'
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: site
    state: present

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_hostname: false
    host: 10.10.10.101
    name: user
    password: 12345aaa
    priv: '*.*:ALL,GRANT'
    state: present

- name: Enable access from web server
  ini_file:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    option: bind-address
    section: null
    value: 0.0.0.0
    backup: yes
  notify:
  - restart mysql
