---

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure Apache is installed on Debian.
  apt:
    name: "{{ apache_packages }}"
    state: present

- name: Ensure PHP is installed on Debian.
  apt:
    name: "{{ php_packages }}"
    state: present

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: "{{ apache_enabled }}"

- git:
    repo: git@github.com:FaztWeb/php-mysql-crud.git
    dest: /home/user