---

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure Apache is installed on Debian.
  apt:
    name: "{{ apache_packages }}"
    state: present

- name: Ensure PHP is installed on Debian.
  apt:
    name: "{{ php_packages }}"
    state: present

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: "{{ apache_enabled }}"

- name: Removing
  file:
    path: /var/www/html
    state: absent

- git:
    repo: https://github.com/FaztWeb/php-mysql-crud.git
    dest: /var/www/html

- replace:
    path: /var/www/html/db.php
    regexp: localhost
    replace: 10.10.10.102
    backup: no

- replace:
    path: /var/www/html/db.php
    regexp: root
    replace: user
    backup: no

- replace:
    path: /var/www/html/db.php
    regexp: password123
    replace: 12345aaa
    backup: no

- replace:
    path: /var/www/html/db.php
    regexp: php_mysql_crud
    replace: site
    backup: no